# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ME8gZ2S4gZBxFwOWRBmZWo0ZoINgO4es
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect('student_management.db')
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE students (
    id INTEGER PRIMARY KEY,
    name TEXT,
    age INTEGER
)
""")

cursor.execute("""
CREATE TABLE courses (
    id INTEGER PRIMARY KEY,
    name TEXT
)
""")

cursor.execute("""
CREATE TABLE enrollments (
    student_id INTEGER,
    course_id INTEGER,
    grade INTEGER,
    FOREIGN KEY(student_id) REFERENCES students(id),
    FOREIGN KEY(course_id) REFERENCES courses(id)
)
""")

students = [
    (1,'Alice',20),
    (2,'Bob',21),
    (3,'Charlie',22),
    (4,'David',20),
    (5,'Eva',21)
]

cursor.executemany(
    "INSERT INTO students VALUES (?,?,?)",
    students
)

courses = [
    (1,'Python'),
    (2,'SQL'),
    (3,'Data Analytics')
]

cursor.executemany(
    "INSERT INTO courses VALUES (?,?)",
    courses
)

enrollments = [
    (1,1,85),
    (1,2,90),
    (2,1,75),
    (2,3,35),
    (3,2,88),
    (3,3,92),
    (4,1,25),
    (4,2,45),
    (5,3,78)
]

cursor.executemany(
    "INSERT INTO enrollments VALUES (?,?,?)",
    enrollments
)

conn.commit()

query1 = """
SELECT c.name AS Course,
       s.name AS Student,
       e.grade
FROM enrollments e
JOIN students s
ON e.student_id = s.id
JOIN courses c
ON e.course_id = c.id
ORDER BY c.name,s.name
"""

df1 = pd.read_sql_query(query1, conn)
print(df1)

query2 = """
SELECT c.name AS Course,
       AVG(e.grade) AS Average_Grade
FROM enrollments e
JOIN courses c
ON e.course_id = c.id
GROUP BY c.name
"""

df2 = pd.read_sql_query(query2, conn)
print(df2)

query3 = """
SELECT s.name,
       AVG(e.grade) AS Avg_Grade
FROM students s
JOIN enrollments e
ON s.id = e.student_id
GROUP BY s.id,s.name
ORDER BY Avg_Grade DESC
LIMIT 3
"""

df3 = pd.read_sql_query(query3, conn)
print(df3)

query4 = """
SELECT COUNT(DISTINCT student_id) AS Failed_Students
FROM enrollments
WHERE grade < 40
"""

df4 = pd.read_sql_query(query4, conn)
print(df4)

conn.close()